package autoGeneratedTests;

import java.util.Set;
import org.junit.jupiter.api.Test;

public class ExampleTemplate {

    @Test
    public void testRepeatedChar() {
//        Set<Character> resultSet = StringUtils.duplicateLetters("software testing");
//        assertTrue(resultSet.contains('t'));

    }

    @Test
    public void testNonRepeatedChar() {
//        Set<Character> resultSet = StringUtils.duplicateLetters("software debugging");
//        assertFalse(resultSet.contains('t'));
    }
}
