package autoGeneratedTests;

import org.junit.jupiter.api.Test;
import assignmentFiles.subjectFiles.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class TestTriangleMCDC {

    @Test()
    public void classify1() {
        Triangle.Type var = Triangle.classify(13, 2, -7);
        assertEquals(Triangle.Type.INVALID, var);
    }

    @Test()
    public void classify2() {
        Triangle.Type var = Triangle.classify(13, 8, 10);
        assertEquals(Triangle.Type.SCALENE, var);
    }

    @Test()
    public void classify3() {
        Triangle.Type var = Triangle.classify(-2, 4, 0);
        assertEquals(Triangle.Type.INVALID, var);
    }

    @Test()
    public void classify4() {
        Triangle.Type var = Triangle.classify(7, 2, 8);
        assertEquals(Triangle.Type.SCALENE, var);
    }

    @Test()
    public void classify5() {
        Triangle.Type var = Triangle.classify(7, 11, 10);
        assertEquals(Triangle.Type.SCALENE, var);
    }
}
