package autoGeneratedTests;

import org.junit.jupiter.api.Test;
import assignmentFiles.subjectFiles.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class TestCalendarMCDC {

    @Test()
    public void daysBetweenTwoDates1() {
        int var = Calendar.daysBetweenTwoDates(-6, -3, 2, 3, -9, -12);
        assertEquals(3286, var);
    }

    @Test()
    public void daysBetweenTwoDates2() {
        int var = Calendar.daysBetweenTwoDates(10, 13, 12, -6, -1, -1);
        assertEquals(6189, var);
    }

    @Test()
    public void daysBetweenTwoDates3() {
        int var = Calendar.daysBetweenTwoDates(11, -12, -2, -11, 2, 9);
        assertEquals(7996, var);
    }

    @Test()
    public void daysBetweenTwoDates4() {
        int var = Calendar.daysBetweenTwoDates(-15, -5, 7, -2, 0, -9);
        assertEquals(4742, var);
    }

    @Test()
    public void daysBetweenTwoDates5() {
        int var = Calendar.daysBetweenTwoDates(15, -11, 14, -11, 8, 13);
        assertEquals(9285, var);
    }

    @Test()
    public void daysBetweenTwoDates6() {
        int var = Calendar.daysBetweenTwoDates(-12, -3, 4, -13, -6, 5);
        assertEquals(364, var);
    }

    @Test()
    public void daysBetweenTwoDates7() {
        int var = Calendar.daysBetweenTwoDates(-5, 8, -10, 14, 2, -13);
        assertEquals(6759, var);
    }

    @Test()
    public void daysBetweenTwoDates8() {
        int var = Calendar.daysBetweenTwoDates(-6, 3, -5, -1, -6, -11);
        assertEquals(1767, var);
    }

    @Test()
    public void daysBetweenTwoDates9() {
        int var = Calendar.daysBetweenTwoDates(-4, -12, 1, -4, -10, 10);
        assertEquals(9, var);
    }
}
