package autoGeneratedTests;

import org.junit.jupiter.api.Test;
import assignmentFiles.subjectFiles.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class TestBMICalculatorBranch {

    @Test()
    public void calculateSequence0001() // Sequence of 1 & 0 in method name denote order each branch/condition in test is executed as true or false
    {
        BMICalculator.Type var = BMICalculator.calculate(14.108855482976185, -12, 10);
        assertEquals(BMICalculator.Type.UNDERWEIGHT, var);
    }

    @Test()
    public void calculateSequence1001() // Sequence of 1 & 0 in method name denote order each branch/condition in test is executed as true or false
    {
        BMICalculator.Type var = BMICalculator.calculate(5.592841560459107, 2, -12);
        assertEquals(BMICalculator.Type.OVERWEIGHT, var);
    }

    @Test()
    public void calculateSequence1101() // Sequence of 1 & 0 in method name denote order each branch/condition in test is executed as true or false
    {
        BMICalculator.Type var = BMICalculator.calculate(7.610351287417096, -2, 15);
        assertEquals(BMICalculator.Type.OBESE, var);
    }

    @Test()
    public void calculateSequence1111() // Sequence of 1 & 0 in method name denote order each branch/condition in test is executed as true or false
    {
        BMICalculator.Type var = BMICalculator.calculate(15.381464923473192, -1, -12);
        assertEquals(BMICalculator.Type.NORMAL, var);
    }
}
